### ISSUE TITLE
Proposal: Relax new() constraint on TResponse

### ISSUE THREAD

**Issue by dev-Finn** [FastEndpoints/Library#184]
Is the `new()` constraint really needed? Wouldn't `NoContent` if response is `null` suffice?

It feels weird having to implement a public (of all things) default constructor seemingly only because one line of code needs `new()` as guard against null.

**Comment by KennethHoff** [comment]
With the newly added `required` keyword, I believe this request will come a far amount, so I vouch for this.

**Comment by dj-nitehawk** [comment]
try `v4.5.0-beta7` and report back pls...

**Comment by dev-Finn** [comment]
A few quick test seemed to work, only passing `null` directly into `SendOkAsync()` resulted in a NRE, which, in my opinion, is probably okay (since one could easily check if they are passing null and then just abort early or handle it differently).

Here the stacktrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
         at FastEndpoints.Config.<>c.<.cctor>b__67_2(HttpResponse rsp, Object dto, String contentType, JsonSerializerContext jCtx, CancellationToken cancellation)
         at FastEndpoints.HttpResponseExtensions.SendOkAsync[TResponse](HttpResponse rsp, TResponse response, JsonSerializerContext jsonSerializerContext, CancellationToken cancellation)
         at FastEndpoints.Endpoint`2.SendOkAsync(TResponse response, CancellationToken cancellation)
         at TestFastEndpoints.TestEndpoint2.HandleAsync(TestRequest req, CancellationToken ct) in C:\source\repos\TestFastEndpoints\TestRequest.cs:line 38
         at FastEndpoints.Endpoint`2.ExecAsync(HttpContext ctx, EndpointDefinition epDef, CancellationToken cancellation)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by KennethHoff** [comment]
I think throwing an NRE there is probably a good thing. It makes no sense to return `null` and then calling that ok. What does `null` in this context refer to?

**Comment by dev-Finn** [comment]
> What does `null` in this context refer to?

True - any scenario I imagined null being passed is probably a very bad practice (like creating the response somewhere else from where it could be null)

**Comment by dj-nitehawk** [comment]
since `TResponse` has a `notnull` constraint, the ide should display a warning anyway.
