### ISSUE TITLE
Exception when Endpoint (with array as TResponse) returns response without response object

### ISSUE THREAD

**Issue by kristian-kablas** [FastEndpoints/Library#225]
Hello,

if Endpoint's `TResponse` object is an array and it returns response, that does not set Endpoint's `Response` property, following Exception is thrown
```
System.ArgumentException: Type is not supported.
         at System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(Type type)
         at System.Runtime.Serialization.FormatterServices.GetUninitializedObject(Type type)
         at FastEndpoints.Endpoint`2.InitResponseDTO()
         at FastEndpoints.Endpoint`2.get_Response()
         at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

For this simple example
```c#
public sealed class GetUserRolesRequest
{
    public int? UserId { get; set; }
}

public sealed class UserRoleDto
{
    public string? Name { get; set; }
}

public sealed class GetUserRolesEndpoint : Endpoint<GetUserRolesRequest, UserRoleDto[]>
{
    public override void Configure()
    {
        Get("/api/user-roles");
        AllowAnonymous();
    }

    public override async Task HandleAsync(GetUserRolesRequest request, CancellationToken ct)
    {
        var userRoles = GetUserRoles(request);

        if (userRoles is null)
        {
            //Response = Array.Empty<UserRoleDto>();
            await SendNotFoundAsync(ct);
            //await SendForbiddenAsync(ct);
        }
        else
        {
            await SendOkAsync(userRoles, ct);
        }
    }

    private UserRoleDto[]? GetUserRoles(GetUserRolesRequest request)
    {
        if (request.UserId is null)
        {
            return null;
        }

        return new UserRoleDto[] { new() { Name = "role1" } };
    }
}
```
request `GET /api/user-roles?userId=1` returns results
request `GET /api/user-roles` throws exception

As a workaround I can set `Response` property to an empty array and `InitResponseDTO` method will not be called. We could also change all arrays to be lists, but our codebase, that we are porting to FastEndpoint is too big for that.

Do we always need to set `Response` property when we use array type as `TResponse` typeparam (we prefer strongly-typed code) or can this be considered a bug?

**Comment by dj-nitehawk** [comment]
changed the stratergy for initializing the response dto in `v5.1.1-beta2`
should be all good now...
